// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/user","layout":false,"id":"2"},"3":{"name":"登录","path":"/user/login","parentId":"2","id":"3"},"4":{"path":"/welcome","name":"欢迎","icon":"smile","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/generate","name":"公文生成","icon":"editOutlined","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/admin","name":"管理页","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"接口管理","icon":"table","path":"/admin/api","parentId":"6","id":"7"},"8":{"path":"/admin","redirect":"/admin/sub-page","parentId":"6","id":"8"},"9":{"path":"/admin/sub-page","name":"二级管理页","parentId":"6","id":"9"},"10":{"path":"*","layout":false,"id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Generate__index" */'@/pages/Generate/index.tsx')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__ApiInfo__index" */'@/pages/ApiInfo/index.tsx')),
'8': React.lazy(() => import('./EmptyRoute')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/MyWebProject/DocuSmart/frontend/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/MyWebProject/DocuSmart/frontend/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
