// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/MyWebProject/DocuSmart/frontend/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import EditOutlined from 'D:/MyWebProject/DocuSmart/frontend/node_modules/@ant-design/icons/es/icons/EditOutlined';
import CrownOutlined from 'D:/MyWebProject/DocuSmart/frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/MyWebProject/DocuSmart/frontend/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, EditOutlined, CrownOutlined, TableOutlined };
